name: "Continuous Integration"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
env:
  GO_VERSION: "1.23.2"
  TINYGO_VERSION: "v0.34.0"
  SPIN_VERSION: ""
jobs:
  spin:
    runs-on: "ubuntu-latest"
    name: Build Spin App
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: Install TinyGo
        uses: rajatjindal/setup-actions/tinygo@v0.0.1
        with:
          version: "${{ env.TINYGO_VERSION }}"
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          plugins: 
      - name: Build verified-bluesky
        run: spin build
        working-directory: .
      - name: Test Go modules
        shell: bash
        run: |
          while IFS= read -r -d '' module; do
            (cd "$(dirname "$module")" && tinygo test ./...)
          done < <(find . -name go.mod -not -path "./.git/*" -print0)
